from enum import Enum


class Intent(str, Enum):
    HIRING = "HIRING"
    VISA_CHECK = "VISA_CHECK"
    DOCUMENT_CHECK = "DOCUMENT_CHECK"
    CONTACT = "CONTACT"
    BRIEFING = "BRIEFING"
    UNSUPPORTED_VALUE_JUDGMENT = "UNSUPPORTED_VALUE_JUDGMENT"
    UNSUPPORTED_LEGAL_JUDGMENT = "UNSUPPORTED_LEGAL_JUDGMENT"
    UNSUPPORTED_AUTO_SUBMISSION = "UNSUPPORTED_AUTO_SUBMISSION"
