"""p1 core schema

docs/DB_SCHEMA.md §10 P1 코어 18테이블 + §6 파생 뷰 4종 + §5.2 append-only 트리거 2종.
db/schema.sql의 정본 DDL을 SQLAlchemy 모델(app/models/)에서 Alembic autogenerate로 생성한 뒤
(순환 FK cases↔runs 처리 확인 완료 — backend/README.md), 뷰·트리거를 수기로 추가했다.

Revision ID: 0001
Revises:
Create Date: 2026-07-12 21:08:33.909299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('case_code', sa.Text(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('case_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='draft', nullable=False),
    sa.Column('agent_stage', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assignee_user_id', sa.Text(), nullable=True),
    sa.Column('approval_required', sa.Boolean(create_constraint=True, name='ck_cases_approval_required'), server_default='0', nullable=False),
    sa.Column('prepared_by', sa.Text(), server_default='rule', nullable=False),
    sa.Column('prepared_run_id', sa.Text(), nullable=True),
    sa.Column('parent_case_id', sa.Text(), nullable=True),
    sa.Column('guard_note', sa.Text(), nullable=True),
    sa.Column('checked_items', sa.JSON(), nullable=True),
    sa.Column('next_wake_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_wake_condition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("agent_stage IS NULL OR agent_stage IN ('detected','collecting','drafted','awaiting_approval','executed')", name='ck_cases_agent_stage'),
    sa.CheckConstraint("case_type IN ('visa_expiry','missing_document','contract_visa_conflict','reporting_deadline','quota_review','hiring','onboarding','other')", name='ck_cases_case_type'),
    sa.CheckConstraint("prepared_by IN ('agent','rule')", name='ck_cases_prepared_by'),
    sa.CheckConstraint("state IN ('draft','risk_review','approval_pending','returned','human_approved','completed','blocked')", name='ck_cases_state'),
    sa.CheckConstraint('checked_items IS NULL OR json_valid(checked_items)', name='ck_cases_checked_items_json'),
    # cases↔runs 순환 FK — runs 테이블이 아직 없어도 SQLite는 CREATE TABLE 시점에 참조 대상
    # 존재를 검사하지 않는다(FK 강제는 DML 시점의 PRAGMA foreign_keys에서만). db/schema.sql과
    # 동일 패턴 — backend/README.md "테스트는 create_all()을 쓰지 않는다" 참조.
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['prepared_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'case_code', name='ux_cases_company_case_code')
    )
    op.create_index('ix_cases_company_severity_due', 'cases', ['company_id', 'severity', 'due_date'], unique=False)
    op.create_index('ix_cases_company_state', 'cases', ['company_id', 'state'], unique=False)
    op.create_index('ux_cases_reuse', 'cases', ['company_id', 'worker_id', 'case_type', 'due_date'], unique=True, sqlite_where=sa.text("state IN ('draft','risk_review','approval_pending','returned')"))
    op.create_table('companies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('business_number', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('worker_count_band', sa.Text(), server_default='5_20', nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Asia/Seoul', nullable=False),
    sa.Column('briefing_time', sa.Text(), server_default='08:30', nullable=False),
    sa.Column('approval_policy', sa.Text(), server_default='owner_only', nullable=False),
    sa.Column('autonomy_level', sa.Text(), server_default='L2', nullable=False),
    sa.Column('onboarding_step', sa.Text(), server_default='O1', nullable=False),
    sa.Column('onboarding_path', sa.Text(), nullable=True),
    sa.Column('case_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('evidence_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("approval_policy IN ('owner_only','manager_allowed')", name='ck_companies_approval_policy'),
    sa.CheckConstraint("autonomy_level IN ('L1','L2','L3')", name='ck_companies_autonomy_level'),
    sa.CheckConstraint("onboarding_path IS NULL OR onboarding_path IN ('ocr','manual','csv','agency')", name='ck_companies_onboarding_path'),
    sa.CheckConstraint("onboarding_step IN ('O1','O2','O3','O4','O5','done')", name='ck_companies_onboarding_step'),
    sa.CheckConstraint("worker_count_band IN ('lt5','5_20','20_50','gt50')", name='ck_companies_worker_count_band'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=True),
    sa.Column('started_by', sa.Text(), nullable=False),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('started_by_user_id', sa.Text(), nullable=True),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('autonomy', sa.Text(), server_default='medium', nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('question', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('anchor_event_no', sa.Integer(), nullable=True),
    sa.Column('parent_run_id', sa.Text(), nullable=True),
    sa.Column('priority_hint', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("autonomy IN ('low','medium','high')", name='ck_runs_autonomy'),
    sa.CheckConstraint("started_by IN ('user','event')", name='ck_runs_started_by'),
    sa.CheckConstraint("status IN ('queued','running','waiting_question','waiting_approval','completed','failed','cancelled')", name='ck_runs_status'),
    sa.CheckConstraint('question IS NULL OR json_valid(question)', name='ck_runs_question_json'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_case', 'runs', ['case_id'], unique=False)
    op.create_index('ix_runs_company', 'runs', ['company_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('biometric_registered', sa.Boolean(create_constraint=True, name='ck_users_biometric_registered'), server_default='0', nullable=False),
    sa.Column('terms_agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('briefings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_snapshot_hash', sa.Text(), nullable=False),
    sa.Column('rerun_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'briefing_date', name='ux_briefings_company_date')
    )
    op.create_table('citations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('ingest_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chroma_collection', sa.Text(), nullable=True),
    sa.Column('chroma_document_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("grade IN ('A','B','C','E','F')", name='ck_citations_grade'),
    sa.CheckConstraint("status IN ('official','review_needed','stale','internal')", name='ck_citations_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citations_status', 'citations', ['status', 'grade'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('invite_phone', sa.Text(), nullable=True),
    sa.Column('invite_token', sa.Text(), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('owner','manager','viewer','expert')", name='ck_memberships_role'),
    sa.CheckConstraint("status IN ('invited','active','removed')", name='ck_memberships_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='ux_memberships_company_user'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index('ix_memberships_company', 'memberships', ['company_id', 'role'], unique=False)
    op.create_table('next_actions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='ready', nullable=False),
    sa.Column('requires_approval', sa.Boolean(create_constraint=True, name='ck_next_actions_requires_approval'), server_default='0', nullable=False),
    sa.Column('slot', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action_type IN ('request_document','create_handoff','send_message','confirm_status','export_package','complete_case','other')", name='ck_next_actions_action_type'),
    sa.CheckConstraint("kind IN ('approve','draft','detail','thread','package','confirm')", name='ck_next_actions_kind'),
    sa.CheckConstraint("slot IS NULL OR slot IN ('primary','secondary')", name='ck_next_actions_slot'),
    sa.CheckConstraint("state IN ('ready','locked','scheduled','waiting')", name='ck_next_actions_state'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_next_actions_case', 'next_actions', ['case_id'], unique=False)
    op.create_index('ix_next_actions_company', 'next_actions', ['company_id', 'state'], unique=False)
    op.create_index('ux_next_actions_slot', 'next_actions', ['case_id', 'slot'], unique=True, sqlite_where=sa.text('slot IS NOT NULL'))
    op.create_table('run_steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('tool_status', sa.Text(), nullable=True),
    sa.Column('handoff_from', sa.Text(), nullable=True),
    sa.Column('handoff_to', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('thinking','tool_call','guardrail','handoff','replan')", name='ck_run_steps_kind'),
    sa.CheckConstraint("tool_status IS NULL OR tool_status IN ('running','done','failed','blocked')", name='ck_run_steps_tool_status'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='ux_run_steps_run_seq')
    )
    op.create_table('workers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('nationality', sa.Text(), nullable=False),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('visa_type', sa.Text(), server_default='E-9', nullable=False),
    sa.Column('stay_expires_at', sa.Date(), nullable=False),
    sa.Column('contract_ends_at', sa.Date(), nullable=True),
    sa.Column('contact_channel', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.Text(), nullable=True),
    sa.Column('registration_no_masked', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("preferred_language IS NULL OR preferred_language IN ('ko','vi','id','en')", name='ck_workers_preferred_language'),
    sa.CheckConstraint("source IN ('manual','ocr','csv','agency')", name='ck_workers_source'),
    sa.CheckConstraint("status IN ('active','inactive','left')", name='ck_workers_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workers_company', 'workers', ['company_id', 'status'], unique=False)
    op.create_index('ix_workers_stay_expiry', 'workers', ['company_id', 'stay_expires_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('action_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('requested_by_actor', sa.Text(), nullable=False),
    sa.Column('requested_by_user_id', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.Text(), nullable=True),
    sa.Column('on_behalf_of_user_id', sa.Text(), nullable=True),
    sa.Column('identity_method', sa.Text(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("identity_method IS NULL OR identity_method IN ('pin','biometric')", name='ck_approvals_identity_method'),
    sa.CheckConstraint("requested_by_actor IN ('agent','rule','user')", name='ck_approvals_requested_by_actor'),
    sa.CheckConstraint("status IN ('pending','approved','rejected','cancelled')", name='ck_approvals_status'),
    sa.CheckConstraint('checklist IS NULL OR json_valid(checklist)', name='ck_approvals_checklist_json'),
    sa.ForeignKeyConstraint(['action_id'], ['next_actions.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['on_behalf_of_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_approvals_case', 'approvals', ['case_id'], unique=False)
    op.create_index('ix_approvals_company_status', 'approvals', ['company_id', 'status'], unique=False)
    op.create_index('ux_approvals_one_pending', 'approvals', ['action_id'], unique=True, sqlite_where=sa.text("status = 'pending'"))
    op.create_table('briefing_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('briefing_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('briefing_id', 'case_id', name='ux_briefing_items_briefing_case')
    )
    op.create_table('case_citations',
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('citation_id', sa.Text(), nullable=False),
    sa.Column('added_by_actor', sa.Text(), nullable=False),
    sa.Column('added_by_run_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("added_by_actor IN ('agent','rule','user')", name='ck_case_citations_added_by_actor'),
    sa.ForeignKeyConstraint(['added_by_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'citation_id')
    )
    op.create_index('ix_case_citations_citation', 'case_citations', ['citation_id'], unique=False)
    op.create_table('document_requirements',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('case_type', sa.Text(), nullable=False),
    sa.Column('visa_type', sa.Text(), nullable=False),
    sa.Column('required_doc', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(create_constraint=True, name='ck_document_requirements_required'), server_default='1', nullable=False),
    sa.Column('citation_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_type', 'visa_type', 'required_doc', name='ux_document_requirements_key')
    )
    op.create_table('worker_documents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='missing', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('file_ref', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('missing','requested','received','expiring','company_check','pending')", name='ck_worker_documents_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'doc_type', name='ux_worker_documents_worker_doc_type')
    )
    op.create_index('ix_worker_documents_company', 'worker_documents', ['company_id', 'status'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('created_by_run_id', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('approval_id', sa.Text(), nullable=True),
    sa.Column('compliance_checks', sa.JSON(), nullable=True),
    sa.Column('expected_scenarios', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft','revision_requested','pending_approval','approved','rejected','superseded')", name='ck_drafts_status'),
    sa.CheckConstraint('compliance_checks IS NULL OR json_valid(compliance_checks)', name='ck_drafts_compliance_checks_json'),
    sa.CheckConstraint('expected_scenarios IS NULL OR json_valid(expected_scenarios)', name='ck_drafts_expected_scenarios_json'),
    sa.CheckConstraint('sent_at IS NULL', name='ck_drafts_sent_at_null'),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drafts_case', 'drafts', ['case_id', 'status'], unique=False)
    op.create_table('evidence_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('event_no', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=True),
    sa.Column('action_id', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.Text(), nullable=True),
    sa.Column('actor_display', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('output_hash', sa.Text(), nullable=True),
    sa.Column('hash_algorithm', sa.Text(), server_default='sha256', nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('payload_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("actor_type IN ('system','user','agent','approver')", name='ck_evidence_events_actor_type'),
    sa.CheckConstraint("type IN ('intent_classified','plan_created','tool_executed','rag_retrieved','risk_flagged','approval_requested','approval_decided','review_started','checklist_completed','exported','final_response_generated','briefing_emitted','notification_sent','worker_reply_received','worker_reply_summarized','status_update_confirmed','handoff_generated','package_link_issued','package_link_viewed','delegation_granted','delegation_revoked','role_granted','role_changed','member_invited','member_removed','approval_escalated','autonomy_changed','worker_deleted')", name='ck_evidence_events_type'),
    sa.ForeignKeyConstraint(['action_id'], ['next_actions.id'], ),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'event_no', name='ux_evidence_events_company_event_no')
    )
    op.create_index('ix_evidence_case', 'evidence_events', ['case_id'], unique=False)
    op.create_index('ix_evidence_company_at', 'evidence_events', ['company_id', 'at'], unique=False)
    op.create_index('ix_evidence_request', 'evidence_events', ['request_id'], unique=False)
    op.create_table('draft_variants',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('draft_id', sa.Text(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_revised', sa.Boolean(create_constraint=True, name='ck_draft_variants_is_revised'), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("lang IN ('ko','vi','id','en')", name='ck_draft_variants_lang'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- 아래부터 수기 추가: docs/DB_SCHEMA.md §5.2 append-only 트리거 + §6 파생 뷰 ---

    # evidence_events는 append-only다 — 수정·삭제는 DB 트리거가 차단한다(레거시 결함
    # §12-1 "런타임 ALTER TABLE" 재발 방지와 같은 정신: 규율을 앱 코드가 아니라 스키마가 쥔다).
    op.execute(
        "CREATE TRIGGER evidence_events_no_update BEFORE UPDATE ON evidence_events "
        "BEGIN SELECT RAISE(ABORT, 'evidence_events is append-only'); END"
    )
    op.execute(
        "CREATE TRIGGER evidence_events_no_delete BEFORE DELETE ON evidence_events "
        "BEGIN SELECT RAISE(ABORT, 'evidence_events is append-only'); END"
    )

    # 파생값(dDay·근거 완성도·KPI·파이프라인 집계)은 컬럼으로 저장하지 않는다(§6) — 뷰로 계산한다.
    op.execute(
        "CREATE VIEW v_usable_citations AS "
        "SELECT * FROM citations WHERE grade <> 'F'"
    )
    op.execute(
        "CREATE VIEW v_citation_link_counts AS "
        "SELECT c.id AS citation_id, COUNT(cc.case_id) AS linked_case_count "
        "FROM citations c LEFT JOIN case_citations cc ON cc.citation_id = c.id "
        "GROUP BY c.id"
    )
    op.execute(
        "CREATE VIEW v_case_derived AS "
        "SELECT "
        "  cs.id AS case_id, "
        "  cs.company_id, "
        "  CAST(julianday(cs.due_date) - julianday(date('now')) AS INTEGER) AS d_day, "
        "  (SELECT COUNT(*) FROM worker_documents wd "
        "    WHERE wd.worker_id = cs.worker_id AND wd.status = 'missing') AS missing_doc_count, "
        "  (SELECT COUNT(*) FROM case_citations cc JOIN citations c2 "
        "    ON c2.id = cc.citation_id AND c2.grade <> 'F' "
        "    WHERE cc.case_id = cs.id) AS usable_citation_count "
        "FROM cases cs"
    )
    op.execute(
        "CREATE VIEW v_pipeline_counts AS "
        "SELECT "
        "  company_id, "
        "  COALESCE(agent_stage, "
        "    CASE "
        "      WHEN state IN ('completed','human_approved') THEN 'executed' "
        "      WHEN state IN ('approval_pending','returned','blocked') THEN 'awaiting_approval' "
        "      ELSE 'collecting' "
        "    END) AS stage, "
        "  COUNT(*) AS case_count "
        "FROM cases "
        "GROUP BY company_id, stage"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # 뷰·트리거를 테이블보다 먼저 제거 — 참조 대상이 사라지기 전에 정리
    op.execute("DROP VIEW IF EXISTS v_pipeline_counts")
    op.execute("DROP VIEW IF EXISTS v_case_derived")
    op.execute("DROP VIEW IF EXISTS v_citation_link_counts")
    op.execute("DROP VIEW IF EXISTS v_usable_citations")
    op.execute("DROP TRIGGER IF EXISTS evidence_events_no_delete")
    op.execute("DROP TRIGGER IF EXISTS evidence_events_no_update")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft_variants')
    op.drop_index('ix_evidence_request', table_name='evidence_events')
    op.drop_index('ix_evidence_company_at', table_name='evidence_events')
    op.drop_index('ix_evidence_case', table_name='evidence_events')
    op.drop_table('evidence_events')
    op.drop_index('ix_drafts_case', table_name='drafts')
    op.drop_table('drafts')
    op.drop_index('ix_worker_documents_company', table_name='worker_documents')
    op.drop_table('worker_documents')
    op.drop_table('document_requirements')
    op.drop_index('ix_case_citations_citation', table_name='case_citations')
    op.drop_table('case_citations')
    op.drop_table('briefing_items')
    op.drop_index('ux_approvals_one_pending', table_name='approvals', sqlite_where=sa.text("status = 'pending'"))
    op.drop_index('ix_approvals_company_status', table_name='approvals')
    op.drop_index('ix_approvals_case', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_workers_stay_expiry', table_name='workers')
    op.drop_index('ix_workers_company', table_name='workers')
    op.drop_table('workers')
    op.drop_table('run_steps')
    op.drop_index('ux_next_actions_slot', table_name='next_actions', sqlite_where=sa.text('slot IS NOT NULL'))
    op.drop_index('ix_next_actions_company', table_name='next_actions')
    op.drop_index('ix_next_actions_case', table_name='next_actions')
    op.drop_table('next_actions')
    op.drop_index('ix_memberships_company', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_citations_status', table_name='citations')
    op.drop_table('citations')
    op.drop_table('briefings')
    op.drop_table('users')
    op.drop_index('ix_runs_company', table_name='runs')
    op.drop_index('ix_runs_case', table_name='runs')
    op.drop_table('runs')
    op.drop_table('companies')
    op.drop_index('ux_cases_reuse', table_name='cases', sqlite_where=sa.text("state IN ('draft','risk_review','approval_pending','returned')"))
    op.drop_index('ix_cases_company_state', table_name='cases')
    op.drop_index('ix_cases_company_severity_due', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
